module.exports = [
  {
    id: "ignis_shard",
    name: "Ignis Shard",
    type: "combat",
    description: "Deals 20–30 fire damage to a single enemy.",
    damage: { min: 20, max: 30 },
    cooldown: 3000,
    manaCost: 10,
    unlockLevel: 3,
    flavor: "A focused flame, summoned with a whisper and a snap.",
  },
  {
    id: "shadow_dagger",
    name: "Shadow Dagger",
    type: "combat",
    description: "Pierces defenses, ignoring 10 shield points.",
    damage: { min: 15, max: 25 },
    cooldown: 30,
    manaCost: 8,
    unlockLevel: 2,
    flavor: "A blade from the void, it slips through shadows.",
  },
  {
    id: "arc_bolt",
    name: "Arc Bolt",
    type: "combat",
    description: "Lightning arc that may chain to another enemy.",
    damage: { min: 18, max: 28 },
    cooldown: 40,
    manaCost: 12,
    unlockLevel: 4,
    flavor: "Electricity crackles as the mage’s fingers snap.",
  },
  {
    id: "frost_grasp",
    name: "Frost Grasp",
    type: "combat",
    description: "Slows target and deals cold damage.",
    damage: { min: 12, max: 20 },
    cooldown: 36,
    manaCost: 9,
    unlockLevel: 5,
    flavor: "Cold fingers of magic grip the soul.",
  },
  {
    id: "eldritch_surge",
    name: "Eldritch Surge",
    type: "combat",
    description: "Unleashes raw arcane energy. Damage varies greatly.",
    damage: { min: 10, max: 50 },
    cooldown: 48,
    manaCost: 15,
    unlockLevel: 6,
    flavor: "The surge obeys no law of nature or reason.",
  },
  {
    id: "ember_blast",
    name: "Ember Blast",
    type: "combat",
    description: "Deals AoE fire damage to all enemies.",
    damage: { min: 10, max: 20 },
    cooldown: 60,
    manaCost: 18,
    unlockLevel: 7,
    flavor: "A firestorm erupts from the mage’s palm.",
  },
  {
    id: "venom_spike",
    name: "Venom Spike",
    type: "combat",
    description: "Deals poison damage over time.",
    damage: { min: 5, max: 5, duration: 3 }, // over 3 turns
    cooldown: 36,
    manaCost: 10,
    unlockLevel: 5,
    flavor: "The toxin creeps through veins, unseen.",
  },
  {
    id: "crystal_lance",
    name: "Crystal Lance",
    type: "combat",
    description: "Ignores armor and stuns briefly.",
    damage: { min: 22, max: 22 },
    cooldown: 42,
    manaCost: 14,
    unlockLevel: 6,
    flavor: "A sharpened shard of earth-bound magic.",
  },
  {
    id: "soulstrike",
    name: "Soulstrike",
    type: "combat",
    description: "Deals bonus damage if the enemy is below 50% HP.",
    damage: { min: 20, max: 35 },
    cooldown: 48,
    manaCost: 15,
    unlockLevel: 8,
    flavor: "It strikes the will, not the flesh.",
  },
  {
    id: "astral_blade",
    name: "Astral Blade",
    type: "combat",
    description: "Bypasses shields, deals psychic damage.",
    damage: { min: 25, max: 30 },
    cooldown: 50,
    manaCost: 20,
    unlockLevel: 10,
    flavor: "Carved from the edge of a star’s thought.",
  },
];
